### ISSUE TITLE
S No. 01: dine in settings

### ISSUE THREAD

**Issue by Moodamg** [danich786/danich786#1]
Summary:
When attempting to access the dine-in setting, an error message stating "Application error: a client-side exception has occurred (see the browser console for more information)" is displayed.

Environment:
Desktop

https://github.com/danich786/danich786/assets/168978938/0c82762b-7639-477b-b95e-d824057ef737

**Comment by danich786** [comment]
@Moodamg this is working fine on my account on my side.

**Comment by Moodamg** [comment]
@danich786 perfect if it's working and tested
